### ISSUE TITLE
TypeError when trying to run pyimq on example dataset

### ISSUE THREAD

**Issue by awedwards** [sakoho81/pyimagequalityranking#1]
Hi! I am trying to run your code on the example dataset you have provided and unfortunately I am getting the following error (I'm on Linux):

My command:
`pyimq.main --mode=directory --mode=analyze --working-directory=/home/bidc/Documents/mibi/Dataset_1 --file-filter=STED --use-mask --normalize-power`

Error:

`Mode option is ['directory', 'analyze']
Traceback (most recent call last):
  File "/home/bidc/anaconda3/envs/mibi/bin/pyimq.main", line 11, in <module>
    load_entry_point('PyImageQualityRanking==0.1', 'console_scripts', 'pyimq.main')()
  File "/home/bidc/anaconda3/envs/mibi/lib/python3.8/site-packages/PyImageQualityRanking-0.1-py3.8.egg/pyimq/bin/main.py", line 166, in main
  File "/home/bidc/anaconda3/envs/mibi/lib/python3.8/site-packages/PyImageQualityRanking-0.1-py3.8.egg/pyimq/filters.py", line 141, in set_smoothing_kernel_size
TypeError: '<' not supported between instances of 'list' and 'tuple'`

**Comment by awedwards** [comment]
I was able to fix this issue by casting the self.dimensions attribute to a list in the assertion (filters.py, line 141):

`
assert self.kernel_size < self.dimensions, \
`
to
`
assert self.kernel_size < list(self.dimensions), \
`

**Comment by sakoho81** [comment]
I fixed that and a couple of other bugs that had appeared with newer Python versions.
