### ISSUE TITLE
TypeError when defining file-filter

### ISSUE THREAD

**Issue by aguycalledankit** [sakoho81/pyimagequalityranking#2]
Hi @sakoho81, I have been testing Pyimq with your Dataset_1. While using the following command to sort data:
`pyimq.main --mode=plot --working-directory=D:\Pyimq_Git\Examples\Dataset_1 --file-filter=2022-02-21_PyIQ_output\18-41-28_PyIQ_analyze_out.csv --result=average`

I'm getting this error:
`Traceback (most recent call last):
  File "C:\Users\ankit\AppData\Local\Programs\Python\Python38\Scripts\pyimq.main-script.py", line 33, in <module>
    sys.exit(load_entry_point('pyimq==0.1', 'console_scripts', 'pyimq.main')())
  File "c:\users\ankit\appdata\local\programs\python\python38\lib\site-packages\pyimq\bin\main.py", line 236, in main
    file_path = os.path.join(options.working_directory, options.file)
  File "c:\users\ankit\appdata\local\programs\python\python38\lib\ntpath.py", line 117, in join
    genericpath._check_arg_types('join', path, *paths)
  File "c:\users\ankit\appdata\local\programs\python\python38\lib\genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'`

I must point out that I don't see this error when I run the whole analysis at once. I'm using Windows btw.

**Comment by aguycalledankit** [comment]
I am also getting the same error on macOS.
